language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  # version bable builds to
  - '8'
before_install:
  - export PATH="$HOME/.yarn/bin:$PATH"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
install:
  - yarn --ignore-engines
before_script:
  # build to user's version then test on that
  - yarn build
script:
  - yarn ci
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
